/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiStreamRouteImport } from './routes/api/stream'
import { Route as ApiSettingsRouteImport } from './routes/api/settings'
import { Route as ApiRunBackendRouteImport } from './routes/api/run-backend'
import { Route as ApiCompileRouteImport } from './routes/api/compile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamRoute = ApiStreamRouteImport.update({
  id: '/api/stream',
  path: '/api/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsRoute = ApiSettingsRouteImport.update({
  id: '/api/settings',
  path: '/api/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunBackendRoute = ApiRunBackendRouteImport.update({
  id: '/api/run-backend',
  path: '/api/run-backend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompileRoute = ApiCompileRouteImport.update({
  id: '/api/compile',
  path: '/api/compile',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/compile': typeof ApiCompileRoute
  '/api/run-backend': typeof ApiRunBackendRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/stream': typeof ApiStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/compile': typeof ApiCompileRoute
  '/api/run-backend': typeof ApiRunBackendRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/stream': typeof ApiStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/compile': typeof ApiCompileRoute
  '/api/run-backend': typeof ApiRunBackendRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/stream': typeof ApiStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/compile'
    | '/api/run-backend'
    | '/api/settings'
    | '/api/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/compile'
    | '/api/run-backend'
    | '/api/settings'
    | '/api/stream'
  id:
    | '__root__'
    | '/'
    | '/api/compile'
    | '/api/run-backend'
    | '/api/settings'
    | '/api/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCompileRoute: typeof ApiCompileRoute
  ApiRunBackendRoute: typeof ApiRunBackendRoute
  ApiSettingsRoute: typeof ApiSettingsRoute
  ApiStreamRoute: typeof ApiStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream': {
      id: '/api/stream'
      path: '/api/stream'
      fullPath: '/api/stream'
      preLoaderRoute: typeof ApiStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings': {
      id: '/api/settings'
      path: '/api/settings'
      fullPath: '/api/settings'
      preLoaderRoute: typeof ApiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/run-backend': {
      id: '/api/run-backend'
      path: '/api/run-backend'
      fullPath: '/api/run-backend'
      preLoaderRoute: typeof ApiRunBackendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/compile': {
      id: '/api/compile'
      path: '/api/compile'
      fullPath: '/api/compile'
      preLoaderRoute: typeof ApiCompileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCompileRoute: ApiCompileRoute,
  ApiRunBackendRoute: ApiRunBackendRoute,
  ApiSettingsRoute: ApiSettingsRoute,
  ApiStreamRoute: ApiStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
